# Generated by Django 4.0.4 on 2022-06-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tychy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='floor',
        ),
    ]
