# Generated by Django 4.0.4 on 2022-06-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tychy', '0002_remove_flat_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
