"""Flat

Revision ID: 16541e55ebe7
Revises: 
Create Date: 2022-05-20 12:42:31.211597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "16541e55ebe7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tychy_flat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link", sa.String(length=300), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("localization", sa.String(length=300), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("rent", sa.Integer(), nullable=True),
        sa.Column("rooms", sa.Integer(), nullable=True),
        sa.Column("space", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=300), nullable=True),
        sa.Column("ownership", sa.String(length=300), nullable=True),
        sa.Column("heating", sa.String(length=300), nullable=True),
        sa.Column("car_park", sa.Boolean(), nullable=True),
        sa.Column("market", sa.String(length=300), nullable=True),
        sa.Column("advertiser_type", sa.String(length=300), nullable=True),
        sa.Column("type_of_building", sa.String(length=300), nullable=True),
        sa.Column("elevator", sa.Boolean(), nullable=True),
        sa.Column("flat_window", sa.String(length=300), nullable=True),
        sa.Column("build_year", sa.Integer(), nullable=True),
        sa.Column("building_material", sa.String(length=300), nullable=True),
        sa.Column("additionals", sa.String(length=3000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tychy_flat")
    # ### end Alembic commands ###
