"""add date

Revision ID: 2cb6f02dcf88
Revises: ec9e012c7dfb
Create Date: 2022-05-21 17:43:57.288082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb6f02dcf88'
down_revision = 'ec9e012c7dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tychy_flat', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tychy_flat', 'date')
    # ### end Alembic commands ###
