"""empty message

Revision ID: 861137c2ecae
Revises: 
Create Date: 2022-07-01 09:44:40.450115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861137c2ecae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flats_districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=3000), nullable=True),
    sa.Column('flat_number', sa.Integer(), nullable=True),
    sa.Column('flat_average_price', sa.Float(), nullable=True),
    sa.Column('flat_average_rent', sa.Float(), nullable=True),
    sa.Column('flat_m2_average_price', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flats_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flat_number', sa.Integer(), nullable=True),
    sa.Column('flat_average_price', sa.Float(), nullable=True),
    sa.Column('flat_average_rent', sa.Float(), nullable=True),
    sa.Column('flat_m2_average_price', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flats_streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=3000), nullable=True),
    sa.Column('flat_number', sa.Integer(), nullable=True),
    sa.Column('flat_average_price', sa.Float(), nullable=True),
    sa.Column('flat_average_rent', sa.Float(), nullable=True),
    sa.Column('flat_m2_average_price', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tychy_flat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('localization', sa.String(length=300), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('rent', sa.Integer(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('space', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=300), nullable=True),
    sa.Column('floor', sa.PickleType(), nullable=True),
    sa.Column('ownership', sa.String(length=300), nullable=True),
    sa.Column('heating', sa.String(length=300), nullable=True),
    sa.Column('car_park', sa.Boolean(), nullable=True),
    sa.Column('market', sa.String(length=300), nullable=True),
    sa.Column('advertiser_type', sa.String(length=300), nullable=True),
    sa.Column('type_of_building', sa.String(length=300), nullable=True),
    sa.Column('elevator', sa.Boolean(), nullable=True),
    sa.Column('flat_window', sa.String(length=300), nullable=True),
    sa.Column('flat_media', sa.String(length=3000), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('building_material', sa.String(length=300), nullable=True),
    sa.Column('additionals', sa.String(length=3000), nullable=True),
    sa.Column('district', sa.String(length=3000), nullable=True),
    sa.Column('street', sa.String(length=3000), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flat_picture',
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=False),
    sa.Column('original', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['tychy_flat.id'], ),
    sa.PrimaryKeyConstraint('width', 'height', 'flat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flat_picture')
    op.drop_table('tychy_flat')
    op.drop_table('flats_streets')
    op.drop_table('flats_statistics')
    op.drop_table('flats_districts')
    # ### end Alembic commands ###
