"""flatv3

Revision ID: ec9e012c7dfb
Revises: 16541e55ebe7
Create Date: 2022-05-21 15:04:58.363214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9e012c7dfb'
down_revision = '16541e55ebe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tychy_flat', sa.Column('floor', sa.PickleType(), nullable=True))
    op.add_column('tychy_flat', sa.Column('flat_media', sa.String(length=3000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tychy_flat', 'flat_media')
    op.drop_column('tychy_flat', 'floor')
    # ### end Alembic commands ###
